version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://socket:8000/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mynetwork

networks:
  mynetwork:
