import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { api } from "~/utils/api";

export default function Home() {
  const { data, isLoading } = api.example.hello.useQuery({ text: "from tRPC" });
  const router = useRouter();

  if (isLoading) return <div>Loading...</div>;
  return (
    <>
      <Head>
        <title>Google Docs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="flex min-h-screen flex-col">
        <div className="mt-5 flex  flex-col  items-center py-2">
          <h2 className="text-3xl font-bold">Google Docs</h2>
        </div>

        <div className="flex  flex-col items-center justify-center py-2">
          <h1 className="text-3xl font-bold">Welcome to Google Docs</h1>
          <p className="mt-3 text-xl">
            Get started by editing{" "}
            <code className="rounded-md bg-gray-100 p-3 font-mono text-lg">
              pages/index.tsx
            </code>
          </p>
          <div className="mt-3 flex w-3/4 flex-wrap items-center justify-center gap-5 ">
            {Array.from({ length: 30 }).map((_, i) => (
              <div
                className="flex flex-col items-center justify-center rounded-xl border border-black p-5"
                key={i}
                onClick={() => void router.push(`/docs/${i}`)}
              >
                <h2 className="text-2xl font-bold">tRPC</h2>
                <p className="mt-3 text-xl">{i}</p>
              </div>
            ))}
          </div>
        </div>
      </body>
    </>
  );
}
